<?php
class GlobalConstants {
	
	const CACHE_AUDITOR = 'CACHE_AUDITOR';
	
	const CACHE_BUYER = 'CACHE_BUYER';
	
	const CACHE_CATEGORY = 'CACHE_CATEGORY';
	const CACHE_CATEGORY_SUBCAT = 'CACHE_CATEGORY_SUBCAT';
	
	const CACHE_SUBCAT = 'CACHE_SUBCAT_';
	
	const CACHE_OPTION1 = 'CACHE_OPTION1';
	const CACHE_OPTION2 = 'CACHE_OPTION2';
	const CACHE_OPTION3 = 'CACHE_OPTION3';
	const CACHE_OPTION4 = 'CACHE_OPTION4';
	const CACHE_OPTION5 = 'CACHE_OPTION5';
	const CACHE_OPTION6 = 'CACHE_OPTION6';
	const CACHE_OPTION7 = 'CACHE_OPTION7';
	const CACHE_OPTION8 = 'CACHE_OPTION8';
	const CACHE_OPTION9 = 'CACHE_OPTION9';
	const CACHE_OPTION10 = 'CACHE_OPTION10';
	const CACHE_OPTION11 = 'CACHE_OPTION11';
	const CACHE_OPTION12 = 'CACHE_OPTION12';
}